-- ==========================================
-- Work Calendars Table
-- 稼働カレンダー（休日設定）
-- ==========================================

-- 稼働カレンダーテーブル
create table work_calendars (
  id bigint generated by default as identity primary key,
  tenant_id uuid references tenants(id) on delete cascade not null,
  date date not null,
  is_holiday boolean not null default false,
  note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  -- テナント内で同じ日付が重複しないように制約
  unique(tenant_id, date)
);

-- インデックス作成（パフォーマンス向上のため）
create index idx_work_calendars_tenant_date on work_calendars(tenant_id, date);

-- RLS (Row Level Security) を有効化
alter table work_calendars enable row level security;

-- RLSポリシー: ユーザーは自分の所属するテナントのカレンダーのみ参照可能
create policy "Users can view their tenant's work calendars"
  on work_calendars
  for select
  using (
    tenant_id in (
      select tenant_id
      from organization_members
      where user_id = auth.uid()
    )
  );

-- RLSポリシー: ユーザーは自分の所属するテナントのカレンダーを作成可能
create policy "Users can insert their tenant's work calendars"
  on work_calendars
  for insert
  with check (
    tenant_id in (
      select tenant_id
      from organization_members
      where user_id = auth.uid()
    )
  );

-- RLSポリシー: ユーザーは自分の所属するテナントのカレンダーを更新可能
create policy "Users can update their tenant's work calendars"
  on work_calendars
  for update
  using (
    tenant_id in (
      select tenant_id
      from organization_members
      where user_id = auth.uid()
    )
  );

-- RLSポリシー: ユーザーは自分の所属するテナントのカレンダーを削除可能
create policy "Users can delete their tenant's work calendars"
  on work_calendars
  for delete
  using (
    tenant_id in (
      select tenant_id
      from organization_members
      where user_id = auth.uid()
    )
  );
