-- ==========================================
-- Create customers table
-- ==========================================
create table customers (
  id bigint generated by default as identity primary key,
  tenant_id uuid references tenants(id) not null,
  name text not null,
  alias text,
  representative_name text,
  phone_number text,
  email text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ==========================================
-- Add customer_id to orders table
-- ==========================================
alter table orders add column customer_id bigint references customers(id);

-- ==========================================
-- Enable RLS for customers table
-- ==========================================
alter table customers enable row level security;

-- ==========================================
-- RLS Policy for customers
-- ==========================================
create policy "Tenant isolation for customers"
  on customers
  for all
  using ( is_tenant_member(tenant_id) )
  with check ( is_tenant_member(tenant_id) );

-- ==========================================
-- Index for better performance
-- ==========================================
create index idx_customers_tenant_id on customers (tenant_id);
create index idx_orders_customer_id on orders (customer_id);
